### ISSUE TITLE
Config tempest.py fails

### ISSUE THREAD

**Issue by Stef1010** [redhat-openstack/python-tempestconf#6]
On RHOS 13 ( queens) 
python config_tempest/config_tempest.py identity.uri $OS_AUTH_URL identity.admin_password $OS_PASSWORD DEFAULT.use_stderr true identity.region regionOne validation.run_validation True --create
 
2018-01-31 15:32:54.494 169 INFO tempest [-] Using tempest config file /etc/tempest/tempest.conf
2018-01-31 15:32:54.513 169 INFO __main__ [-] Reading defaults from file '/home/centos/redhat-tempest/python-tempestconf/etc/default-overrides.conf'
2018-01-31 15:32:55.017 169 INFO tempest.lib.common.rest_client [req-ff0ca68a-a31f-4bf3-8ca0-47be5c7ae73e ] Request (main): 201 POST http://10.0.0.105:5000//v3/auth/tokens
2018-01-31 15:32:55.143 169 INFO tempest.lib.common.rest_client [req-6cd5fb02-6dc2-4ec2-9b1b-14bd73b33da9 ] Request (main): 200 GET http://192.168.24.11:35357/v3/projects 0.125s
2018-01-31 15:32:56.395 169 CRITICAL tempest [-] Unhandled error: IndexError: list index out of range
2018-01-31 15:32:56.395 169 ERROR tempest Traceback (most recent call last):
2018-01-31 15:32:56.395 169 ERROR tempest   File "config_tempest/config_tempest.py", line 1112, in <module>
2018-01-31 15:32:56.395 169 ERROR tempest     main()
2018-01-31 15:32:56.395 169 ERROR tempest   File "config_tempest/config_tempest.py", line 187, in main
2018-01-31 15:32:56.395 169 ERROR tempest     'disable_ssl_certificate_validation'
2018-01-31 15:32:56.395 169 ERROR tempest   File "/home/centos/redhat-tempest/python-tempestconf/config_tempest/api_discovery.py", line 246, in discover
2018-01-31 15:32:56.395 169 ERROR tempest     ep = entry['endpoints'][0]
2018-01-31 15:32:56.395 169 ERROR tempest IndexError: list index out of range
2018-01-31 15:32:56.395 169 ERROR tempest

**Comment by kopecmartin** [comment]
Hello, 
this tool was moved to https://github.com/openstack/python-tempestconf, please use the new, the issue is fixed there.

**Comment by apevec** [comment]
python-tempestconf is moved to OpenStack http://git.openstack.org/cgit/openstack/python-tempestconf Please use OpenStack gerrit https://review.openstack.org to submit patches.
